### PR TITLE
Improve the code a little bit

### PR DESCRIPTION
**Pull request by oerdnj**

### CODE REVIEW

**Comment by darkbasic** [comment]
LOL

**Comment by mastercoms** [comment]
This isn't helping him. It is better for him to continue, he will get a better learning experience out of it.

**Comment by oerdnj** [comment]
@mastercoms It's definitely not helping him to have this in the public or present this anywhere. I am sorry to say that, but he would only embarrass himself even more.

If he wants to learn something he should start with humility and perhaps then moving to math and cryptography. Making such bold claims as he had without any knowledge in the field is just a waste of time of many people. And he should know better, he is a no longer a teenager.

Anyway no reason why to keep this open or waste any more time on this.

**Comment by mastercoms** [comment]
Does it really have any consequence to him? The internet allows for anonymity. If he gives up, he can start over with a new Internet identity. Perhaps making this won't teach him much about encryption, but it will most certainly teach him about humility, as you said.

**Comment by oerdnj** [comment]
He did this under his real name and you can link this to (at least) his LinkedIn profile where he has a picture of him (with cats). Not sure if he is that anonymous anymore... 

On 20 Nov 2015, mastercoms <notifications@github.com> wrote:
>Does it really have any consequence to him? The internet allows for
>anonymity. If he gives up, he can start over with a new Internet
>identity. Perhaps making this won't teach him much about encryption,
>but it will most certainly teach him about humility, as you said.
>
>---
>Reply to this email directly or view it on GitHub:
>https://github.com/ikizir/HohhaDynamicXOR/pull/2#issuecomment-158222388

-- 
Sent with <a href="https://play.google.com/store/apps/details?id=com.onegravity.k10.pro2"><b>K-@ Mail</b></a> - the evolution of emailing.

**Comment by mastercoms** [comment]
But he still doesn't have to link a new account to his real name.

**Comment by ed770878** [comment]
@oerdnj @mastercoms may be interested in #13?

**Comment by oerdnj** [comment]
@ed770878 I envy your patience with a guy who is so ignorant to basic principles.

**Comment by mastercoms** [comment]
@oerdnj me too

**Pull request closed without merging**
